theme: jekyll-theme-minimal
title: hydrusImport
description: An R package to import HYDRUS 2D/3D simulation results into R

logo: hydrusImport-logo.png
show_downloads: true
google_analytics: "UA-111480581-1"
